Repository panhachom/Capstone-Project, pull requests merged in 2023-06, with the labels that each got.

#111 Close 110
  app/Http/Controllers/TourListController.php
  database/migrations/2023_06_03_073043_add_views_to_tours.php
  resources/views/admin/booking/index.blade.php
  resources/views/admin/promotion/create.blade.php
  resources/views/admin/promotion/edit.blade.php
  resources/views/admin/promotion/index.blade.php
  routes/web.php
Labels: design, backend

#109 Close #108 enhance admin dashboard
  app/Http/Controllers/AdminDashboardController.php
  resources/css/dashboard.css
  resources/views/admin/dashbaord/index.blade.php
  resources/views/components/dashboard.blade.php
Labels: enhancement, design

#115 Close #114 enhance ui design
  app/Http/Controllers/ActivityController.php
  app/Http/Controllers/ActivityTourController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/PromotionController.php
  app/Http/Controllers/TourListController.php
  database/migrations/2023_05_04_083147_create_tours_table.php
  public/images/promotions/1685456496.webp
  public/images/promotions/1685456586.webp
  public/images/tours/1685454775.jpeg
  public/images/tours/1685455136.jpg
  public/images/tours/1685455259.jpg
  public/images/tours/1685455358.jpg
  public/images/tours/1685455447.jpg
  public/images/tours/1685455536.jpg
  public/images/tours/1685455659.jpg
  public/images/tours/1685455780.jpg
  public/images/tours/1685455927.jpg
  public/images/tours/1685455941.jpg
  public/images/tours/1685455955.jpg
  public/images/tours/1685772129.png
  public/vendor/1685454173.png
  resources/views/about_us/about_us.blade.php
  resources/views/admin/booking/show.blade.php
  resources/views/admin/manage_all_tour/update_all_tour.blade.php
  resources/views/admin/manage_vendor/view_vendor.blade.php
  resources/views/admin/promotion/create.blade.php
  resources/views/admin/user/reset_password_form.blade.php
  resources/views/admin/user/update_user.blade.php
  resources/views/admin_main.blade.php
  resources/views/components/card-component.blade.php
  resources/views/components/navbar.blade.php
  resources/views/home/index.blade.php
  resources/views/tour_list/show.blade.php
  resources/views/vendor/activity/create.blade.php
  resources/views/vendor/activity/edit.blade.php
  resources/views/vendor/booking/edit.blade.php
  resources/views/vendor/category/create.blade.php
  resources/views/vendor/category/edit.blade.php
  resources/views/vendor/show.blade.php
  resources/views/vendor/tours/activity/index.blade.php
  resources/views/vendor/tours/country/index.blade.php
  resources/views/vendor/tours/edit.blade.php
  resources/views/vendor/tours/images/create.blade.php
  resources/views/vendor/tours/tour_date/edit.blade.php
  resources/views/vendor/tours/tour_date/index.blade.php
  routes/web.php
Labels: design

#112 107 wishlist
  app/Http/Controllers/WishlistController.php
  app/Models/Tour.php
  config/markable.php
  database/migrations/2023_06_11_143745_create_favorites_table.php
  public/images/tours/1686500703.jpeg
  public/vendor/1686500422.jpeg
  resources/views/components/card-component.blade.php
  resources/views/components/navbar.blade.php
  resources/views/home/index.blade.php
  resources/views/profile/profile_setting.blade.php
  resources/views/wishlist/index.blade.php
  routes/web.php
Labels: design

#118 Close #117 integate payment with paypal
  app/Http/Controllers/AdminPaymentController.php
  app/Http/Controllers/BookingController.php
  app/Http/Controllers/VendorBookingController.php
  app/Http/Controllers/VendorPaymentController.php
  app/Models/Booking.php
  app/Models/Payment.php
  app/Models/Tour.php
  composer.json
  composer.lock
  database/migrations/2023_05_16_153633_create_bookings_table.php
  database/migrations/2023_06_03_073043_add_views_to_tours.php
  database/migrations/2023_06_10_144158_create_payments_table.php
  public/check.png
  public/images/tours/1686400506.jpeg
  resources/css/app.css
  resources/css/navbar.css
  resources/views/about_us/about_us.blade.php
  resources/views/admin/booking/index.blade.php
  resources/views/admin/booking/show.blade.php
  resources/views/admin/dashbaord/index.blade.php
  resources/views/admin/payment/show.blade.php
  resources/views/app.blade.php
  resources/views/booking/create.blade.php
  resources/views/booking/index.blade.php
  resources/views/components/admin_payment_tabs.blade.php
  resources/views/components/admin_reciept.blade.php
  resources/views/components/modal.blade.php
  resources/views/components/navbar.blade.php
  resources/views/components/payment_tabs.blade.php
  resources/views/components/reciept.blade.php
  resources/views/customer_promotion/show.blade.php
  resources/views/detail_page/index.blade.php
  resources/views/home/index.blade.php
  resources/views/profile/profile_setting.blade.php
  resources/views/tour_list/adventure_category.blade.php
  resources/views/tour_list/cultural_category.blade.php
  resources/views/tour_list/food_and_drink_category.blade.php
  resources/views/tour_list/history_category.blade.php
  resources/views/tour_list/index.blade.php
  resources/views/tour_list/show.blade.php
  resources/views/tour_list/sport_category.blade.php
  resources/views/vendor/booking/index.blade.php
  resources/views/vendor/booking/show.blade.php
  resources/views/vendor/payment/show.blade.php
  resources/views/wishlist/index.blade.php
  routes/web.php
Labels: backend, core

#123 bookingHistory
  app/Http/Controllers/BookingController.php
  resources/views/booking/bookingHistory.blade.php
  resources/views/components/card-component-for-history.blade.php
  routes/web.php
Labels: design
