Repository panhachom/Capstone-Project, pull requests merged in 2023-05, with the labels that each got.

#14 Close #13 List Tour ui design
  app/Http/Controllers/listourController.php
  app/View/Components/CardComponent.php
  resources/css/navbar.css
  resources/views/components/card-component.blade.php
  resources/views/components/card.blade.php
  resources/views/components/footer.blade.php
  resources/views/components/navbar.blade.php
  resources/views/list/list_tour.blade.php
  routes/web.php
Labels: design

#22 Close #21 fix ui bug
  .DS_Store
  app/Http/Controllers/TourListController.php
  public/.DS_Store
  resources/views/.DS_Store
  resources/views/home/index.blade.php
  resources/views/tour_list/index.blade.php
  routes/web.php
Labels: bug

#24 Close #23 add card component to homepage
  resources/views/home/index.blade.php
  resources/views/tour_list/index.blade.php
Labels: bug, enhancement

#32 Close #26 table Integration
  app/Http/Controllers/ActivityController.php
  app/Http/Controllers/CategoryController.php
  app/Http/Controllers/LocationController.php
  app/Http/Controllers/TourController.php
  app/Http/Controllers/TourDateController.php
  app/Http/Controllers/TourImageController.php
  app/Http/Controllers/VendorController.php
  app/Models/Activity.php
  app/Models/Category.php
  app/Models/Location.php
  app/Models/Tour.php
  app/Models/TourDate.php
  app/Models/TourImage.php
  app/Models/Vendor.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2023_05_04_083127_create_vendors_table.php
  database/migrations/2023_05_04_083147_create_tours_table.php
  database/migrations/2023_05_04_083215_create_tour_images_table.php
  database/migrations/2023_05_04_083232_create_tour_dates_table.php
  database/migrations/2023_05_04_083243_create_categories_table.php
  database/migrations/2023_05_04_083258_create_activities_table.php
  database/migrations/2023_05_08_140832_create_locations_table.php
Labels: backend

#48 Close #37 tour post crud
  app/Http/Controllers/TourController.php
  app/Http/Controllers/TourImageController.php
  app/Models/Tour.php
  app/Models/TourImage.php
  public/images/tours/1683956628.png
  resources/css/vendor_main.css
  resources/views/components/tour_tabs.blade.php
  resources/views/vendor/tour/index.blade.php
  resources/views/vendor/tours/create.blade.php
  resources/views/vendor/tours/edit.blade.php
  resources/views/vendor/tours/images/create.blade.php
  resources/views/vendor/tours/images/index.blade.php
  resources/views/vendor/tours/index.blade.php
  resources/views/vendor/tours/show.blade.php
  resources/views/vendor_main.blade.php
  routes/web.php
Labels: design, backend

#51 close #50 fix tour crud bug
  app/Http/Controllers/TourController.php
  resources/views/vendor/tours/create.blade.php
Labels: bug

#57 close #56-Add-activity-to-tour
  app/Http/Controllers/ActivityTourController.php
  app/Models/ActivityTour.php
  app/Models/Tour.php
  database/migrations/2023_05_11_065131_create_activity_tour_table.php
  resources/views/components/tour_tabs.blade.php
  resources/views/vendor/tours/activity/index.blade.php
  routes/web.php
Labels: backend

#64 Close #63-update-user-management
  app/Http/Controllers/ResetPasswordController.php
  app/Http/Controllers/UserController.php
  app/Mail/my_test_email.php
  app/Models/User.php
  app/Notifications/reset_password_notifications.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/user/reset_password.blade.php
  resources/views/admin/user/reset_password_form.blade.php
  resources/views/admin_main.blade.php
  resources/views/components/footer.blade.php
  routes/web.php
Labels: core

#73 close #72 VendorManagement
  app/Http/Controllers/AdminVendorController.php
  app/Models/User.php
  app/Models/Vendor.php
  database/migrations/2023_05_04_083127_create_vendors_table.php
  resources/views/admin/manage_vendor/create_vendor.blade.php
  resources/views/admin/manage_vendor/update_vendor.blade.php
  resources/views/admin/manage_vendor/view_vendor.blade.php
  resources/views/admin/test.blade.php
  resources/views/admin/user/view_user.blade.php
  resources/views/admin_main.blade.php
  routes/web.php
Labels: backend

#75 Close #74 booking flow
  app/Http/Controllers/BookingController.php
  app/Http/Controllers/ProfilesettingController.php
  app/Http/Controllers/TourListController.php
  app/Http/Controllers/VendorBookingController.php
  app/Models/Booking.php
  app/Models/Tour.php
  app/Models/User.php
  app/View/Components/CardComponent.php
  database/migrations/2023_05_04_083147_create_tours_table.php
  database/migrations/2023_05_16_153633_create_bookings_table.php
  database/migrations/2023_05_18_150750_add_booking_number_to_bookings_table.php
  database/migrations/2023_05_18_152326_create_booking_tour_table.php
  database/migrations/2023_05_19_154629_add_in_stock_to_tour_table.php
  database/seeders/CategorySeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/UserSeeder.php
  resources/css/vendor_main.css
  resources/views/admin_main.blade.php
  resources/views/app.blade.php
  resources/views/auth/login.blade.php
  resources/views/booking/create.blade.php
  resources/views/booking/index.blade.php
  resources/views/components/booking_tabs.blade.php
  resources/views/components/card-component.blade.php
  resources/views/components/navbar.blade.php
  resources/views/components/tour_tabs.blade.php
  resources/views/profile/profile_setting.blade.php
  resources/views/tour_list/index.blade.php
  resources/views/tour_list/show.blade.php
  resources/views/vendor/activity/edit.blade.php
  resources/views/vendor/activity/index.blade.php
  resources/views/vendor/booking/approved_booking.blade.php
  resources/views/vendor/booking/edit.blade.php
  resources/views/vendor/booking/index.blade.php
  resources/views/vendor/booking/unapproved_booking.blade.php
  resources/views/vendor/index.blade.php
  resources/views/vendor/tours/activity/index.blade.php
  resources/views/vendor/tours/country/index.blade.php
  resources/views/vendor/tours/edit.blade.php
  resources/views/vendor/tours/images/index.blade.php
  resources/views/vendor/tours/index.blade.php
  resources/views/vendor/tours/tour_date/index.blade.php
  resources/views/vendor_main.blade.php
  routes/web.php
Labels: backend

#86 Close #85
  app/Http/Controllers/ActivityController.php
  app/Http/Controllers/PromotionController.php
  resources/views/admin/promotion/create.blade.php
  resources/views/admin/promotion/edit.blade.php
  resources/views/admin/promotion/index.blade.php
  resources/views/admin_main.blade.php
  resources/views/vendor/activity/index.blade.php
  routes/web.php
Labels: design, backend

#90 Close #89
  app/Http/Controllers/AdminBookingController.php
  resources/views/admin/booking/index.blade.php
  resources/views/admin/booking/show.blade.php
  resources/views/admin/promotion/index.blade.php
  resources/views/admin_main.blade.php
  resources/views/booking/index.blade.php
  routes/web.php
Labels: design, backend

#95 sort function
  app/Http/Controllers/HomeController.php
  resources/views/home/index.blade.php
  routes/web.php
Labels: backend

#93 send email
  app/Http/Controllers/BookingController.php
  resources/views/mail/BookingMail.blade.php
  resources/views/vendor/show.blade.php
  resources/views/vendor_main.blade.php
Labels: backend

#100 Close #98 detail page responsive
  resources/views/tour_list/show.blade.php
Labels: design

#101 Close #71 seeding
  database/seeders/CategorySeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/UserSeeder.php
Labels: backend
